language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  # - npm run lint
  #- npm run test:headless
  - npm run build --prod --base-href /angular-admin-lte/  
  # - xvfb-run npm run e2e

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist/angular-admin-lte-demo
  on:
    branch: master
