language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

env:
  global:
  - TMPDIR=/tmp

cache:
  directories:
    - node_modules

addons:
  chrome: stable

before_script:
  #- yarn global add @angular/cli

before_deploy:
  # - yarn gh-pages $TMPDIR/gh-pages --target $TRAVIS_BRANCH

script:
  # - npm run lint
  # - npm run test:headless
  - ng build angular-admin-lte-demo --prod --base-href="/angular-admin-lte/$([ "$TRAVIS_PULL_REQUEST" != false ] && echo "pulls/$TRAVIS_PULL_REQUEST/" || echo "branches/$TRAVIS_BRANCH/")"
  - bash scripts/gh-pages.sh $TMPDIR/gh-pages $TRAVIS_BUILD_DIR/dist/angular-admin-lte-demo
# - xvfb-run npm run e2e



deploy:
  provider: pages
  local-dir: $TMPDIR/gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    all_branches: true
