language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable
  
branches:
  only:
  - master
  - develop

before_script:
  - yarn global add @angular/cli

before_deploy:
  - mv dist/angular-admin-lte-demo dist/angular-admin-lte/$TRAVIS_BRANCH

script:
  # - npm run lint
  #- npm run test:headless
  - ng build angular-admin-lte-demo --prod --base-href="/angular-admin-lte/$TRAVIS_BRANCH"
  # - xvfb-run npm run e2e

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
